apiVersion: v1
kind: Service
metadata:
  name: formatter
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
  selector:
    app: formatter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: formatter
spec:
  selector:
    matchLabels:
      app: formatter
  replicas: 1
  template:
    metadata:
      labels:
        app: formatter
    spec:
      containers:
      - name: formatter
        image: docker-compose_formatter:latest
        ports:
        - containerPort: 8081
        imagePullPolicy: Never
