apiVersion: v1
kind: Service
metadata:
  name: publisher
spec:
  type: ClusterIP
  ports:
    - port: 8082
      protocol: TCP
  selector:
    app: publisher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  selector:
    matchLabels:
      app: publisher
  replicas: 1
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher
          image: docker-compose_publisher:latest
          ports:
            - containerPort: 8082
          imagePullPolicy: Never
