apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
spec:
  type: LoadBalancer
  ports:
    - port: 16686
      protocol: TCP
      targetPort: 16686
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-compact
spec:
  type: ClusterIP
  ports:
    - port: 6831
      protocol: UDP
  selector:
    app: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one
        ports:
        - containerPort: 16686
        - containerPort: 6831
          protocol: UDP
